[package]
name = "streaming-harness"
version = "0.1.0"
authors = ["Andrea Lattuada <andrea.lattuada@inf.ethz.ch>"]

[features]
default = []
hdrhist-support = ["streaming-harness-hdrhist"]

[dependencies]
num-traits = "^0.2"
streaming-harness-hdrhist = { version = "^0.2", optional = true }

[dev-dependencies]
timely = "^0.5"
rand = "^0.3.18"

[[example]]
name = "timely-word-count"
required-features = ["hdrhist-support"]
